// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistoryEntries() {
  return window['go']['main']['App']['ClearHistoryEntries']();
}

export function CloseProxy() {
  return window['go']['main']['App']['CloseProxy']();
}

export function ExportCA() {
  return window['go']['main']['App']['ExportCA']();
}

export function GetHistoryEntryDetail(arg1) {
  return window['go']['main']['App']['GetHistoryEntryDetail'](arg1);
}

export function GetHistoryFilterMatchesForEntries(arg1) {
  return window['go']['main']['App']['GetHistoryFilterMatchesForEntries'](arg1);
}

export function RemoveActiveHistoryFilter(arg1) {
  return window['go']['main']['App']['RemoveActiveHistoryFilter'](arg1);
}

export function RemoveHistoryEntry(arg1) {
  return window['go']['main']['App']['RemoveHistoryEntry'](arg1);
}

export function ResetCA() {
  return window['go']['main']['App']['ResetCA']();
}

export function SendRepeaterRequest(arg1) {
  return window['go']['main']['App']['SendRepeaterRequest'](arg1);
}

export function StartProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3);
}

export function UpsertActiveHistoryFilter(arg1) {
  return window['go']['main']['App']['UpsertActiveHistoryFilter'](arg1);
}
