// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {repeater} from '../models';

export function ClearHistoryEntries():Promise<void>;

export function CloseProxy():Promise<void>;

export function ExportCA():Promise<string>;

export function GetHistoryEntryDetail(arg1:number):Promise<bridge.HTTPHistoryEntryDetail>;

export function GetHistoryFilterMatchesForEntries(arg1:bridge.GetHistoryFilterMatchesForEntriesParams):Promise<Array<bridge.HistoryEntryFilterMatches>>;

export function RemoveActiveHistoryFilter(arg1:bridge.RemoveActiveHistoryFilterParams):Promise<void>;

export function RemoveHistoryEntry(arg1:number):Promise<void>;

export function ResetCA():Promise<void>;

export function SendRepeaterRequest(arg1:repeater.RepeaterSendPayload):Promise<repeater.RepeaterSendResult>;

export function StartProxy(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function UpsertActiveHistoryFilter(arg1:bridge.UpsertActiveHistoryFilterParams):Promise<bridge.UpsertActiveHistoryFilterResult>;
